services:
  web_app:
    build:
      context: ./Backend - comparação direta
      dockerfile: Dockerfile
    container_name: paf_analyzer_app
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production 
      - FLASK_DEBUG=0        
      - PORT=5001